" Comments in Vimscript start with a `"`.

" If you open this file in Vim, it'll be syntax highlighted for you.

" Vim is based on Vi. Setting `nocompatible` switches from the default
" Vi-compatibility mode and enables useful Vim functionality. This
" configuration option turns out not to be necessary for the file named
" '~/.vimrc', because Vim automatically enters nocompatible mode if that file
" is present. But we're including it here just in case this config file is
" loaded some other way (e.g. saved as `foo`, and then Vim started with
" `vim -u foo`).
set nocompatible

" Turn on syntax highlighting.
syntax on

" Disable the default Vim startup message.
set shortmess+=I

" Show line numbers.
set number

" Always show the status line at the bottom, even if you only have one window open.
set laststatus=2

" The backspace key has slightly unintuitive behavior by default. For example,
" by default, you can't backspace before the insertion point set with 'i'.
" This configuration makes backspace behave more reasonably, in that you can
" backspace over anything.
set backspace=indent,eol,start

" By default, Vim doesn't let you hide a buffer (i.e. have a buffer that isn't
" shown in any window) that has unsaved changes. This is to prevent you from "
" forgetting about unsaved changes and then quitting e.g. via `:qa!`. We find
" hidden buffers helpful enough to disable this protection. See `:help hidden`
" for more information on this.
set hidden

" This setting makes search case-insensitive when all characters in the string
" being searched are lowercase. However, the search becomes case-sensitive if
" it contains any capital letters. This makes searching more convenient.
set ignorecase
set smartcase

" Enable searching as you type, rather than waiting till you press enter.
set incsearch

" Unbind some useless/annoying default key bindings.
nmap Q <Nop> " 'Q' in normal mode enters Ex mode. You almost never want this.

" Disable audible bell because it's annoying.
set noerrorbells visualbell t_vb=

" Enable mouse support. You should avoid relying on this too much, but it can
" sometimes be convenient.
set mouse+=a

" Make whitespace visible
set list
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·

" Indentation settings
set expandtab
set autoindent
set shiftwidth=0
set tabstop=4

" Enable language-specific config
filetype plugin on

" Reduce delay after pressing <esc>
" https://vi.stackexchange.com/a/20220
set timeoutlen=1000
set ttimeoutlen=50

" Let arrow keys wrap to previous or next line
set whichwrap+=<,>,h,l,[,]

" Indent wrapped lines
set breakindent
set breakindentopt=shift:2,min:40,sbr
set showbreak=>>

" Show that I'm in insert mode
" https://stackoverflow.com/a/6489348
:autocmd InsertEnter * set cursorline
:autocmd InsertLeave * set nocursorline

" Incremental search, highlight search results, and clear highlighting on
" ENTER
set incsearch
set hlsearch
nnoremap <CR> :noh<CR>

" Make Y yank from the cursor to the end of the line (similar to C, D) rather
" than yanking the entire line
:map Y y$

" For some reason, tmux doesn't detect this by default
" https://unix.stackexchange.com/a/363374
set background=dark

" Keep highlight after indenting
vnoremap < <gv
vnoremap > >gv

" Shift+TAB to unindent when in insert mode
inoremap <S-Tab> <C-d>
